### ISSUE TITLE
Issue - Gyms are shown as PokeStops (as tooltips)

### ISSUE THREAD

**Issue by devgraal** [Lunat1q/Catchem-PoGo#1006]
Dont know since which release, but every Gym is displayed and announced as PokeStop.
Anyway, as far as I could test, Trainer dont try to harvest items from those Gyms.

**Comment by ArchangelBr** [comment]
Same here... 
Would be nice if we have an different icon for gym.

By the way, As I read on source, if I touch a Gym, it list for us the info about it. If there is no one hanging there, we could get it. I could not test it yet because never found an empty gym.

Would be nice if we touch it and, if it is from our team and there is an empty spot, put a poke on that and colect the coins.

**Comment by Lunat1q** [comment]
I'll check gym icon.

**Comment by ArchangelBr** [comment]
How about that other sugestion, @Lunat1q  ? To put a poke on Gym if it's from our team and there is a free spot.

Could be interesting...
