### ISSUE TITLE
problem with great and ultra boll

### ISSUE THREAD

**Issue by renanloko** [Lunat1q/Catchem-PoGo#1030]
I 'm not managing to set the bot to not use great and ultra boll.

Can someone help me ?

Ty !!
![sem titulo](https://cloud.githubusercontent.com/assets/21349040/18110677/da6e6e0c-6eef-11e6-86d3-0e7970e2d512.png)

**Comment by delunatix** [comment]
You should edit the Great ball and Ultra ball below catch probability. .35 means it will throw great ball on poke with 35% and below chance. same goes with ultra ball; .2 means throw at poke with 20% chance. So you may want to try lowering it so that it won't throw those balls more often. Mine is set at .2 for great ball and .1 for ultra ball. Hope this helps.
