### ISSUE TITLE
I need help ¿because this happens?

### ISSUE THREAD

**Issue by akiramses** [Lunat1q/Catchem-PoGo#1031]
![sin titulo](https://cloud.githubusercontent.com/assets/21349232/18111156/e51731ca-6ee2-11e6-8def-3b35f38bd7a9.png)

**Comment by Joasow** [comment]
Self problem, the player dont walk.

**Comment by delunatix** [comment]
Try using RouteCreator to build your own route in between pokestops and tick on manual route at the bottom before building it and saving it. Then place it on settings as custom route.

Better yet use 1.4.9.0 for the meantime as the versions after it are quite buggy at the moment.

**Comment by stark93** [comment]
Check that the "Recycle At Usage Percentage" from items settings is NOT a decimal number, for example it must be 85 and not 0.85

**Comment by wagas** [comment]
@stark93  i guess you are wrong? if you put 85 there it would be 8500% of inventory =

**Comment by petoe93** [comment]
it has to be a decimal number between 0 and 1..same with the miss chance and like all other throwing options..

**Comment by vandroiy8** [comment]
i guess it could be a loop if you have set up the limits as 100 balls, 100 potions, 30 berries, 50 revive, and the percentage at 0.85.
Because you got so many incubators, incense etc. the bot cant figure out how to get below 85%, which would be 297/350 by throwing away only 19 pokeballs which would result in 303/350. just a gues or other settings of yours are weird

**Comment by Lunat1q** [comment]
@vandroiy8 thank god some one could understand this.... i'm tired explaining this over and over...
