### ISSUE TITLE
the bot self check the inventory a lot

### ISSUE THREAD

**Issue by catchya** [Lunat1q/Catchem-PoGo#1041]
can you just help to minimize it? take too long time
or set a choice to let ppl pick if they need to check so often

**Comment by iAngelG** [comment]
Make sure the inventory you want to keep in less than your actual max inventory. I had this issue because I put 500 items and my max was 350. When I changed it, it stopped doing that. It may be something else, but that fixed mine.

**Comment by iAngelG** [comment]
Is less*

**Comment by stark93** [comment]
Check that the "Recycle At Usage Percentage" from items settings is NOT a decimal number, for example it must be 85 an not 0.85

**Comment by conkersbr** [comment]
same problem here

![problem](https://cloud.githubusercontent.com/assets/21352145/18114673/5f575c36-6f0f-11e6-9eb8-e4abb53cfb95.jpg)

it checks the inventory three times in a row and takes 1:30 this every pokestop

**Comment by Eichhoernchen123** [comment]
Go to settings and change the number at the option "Recycle At Usage Percentage". Probably you have there 0.85, the default setup. It means, when your items reach 85% (=0.85) of your storage, the bot is going to check the inventory. You can change the value for 1,50 (=150%) (so he's never going to check the inventory anymore because your items will never reach 150% of your storage).
It will fix the problem, it did also to me.
Cheers!

**Comment by Lunat1q** [comment]
You should never set it to 1 or above.
You just messed with settings. How many items to keep, and inv percentage

**Comment by catchya** [comment]
so should raise it to 0.90 up? not 80 or 90?
