### ISSUE TITLE
[Possible Bug] Character is too busy

### ISSUE THREAD

**Issue by felipeuntill** [Lunat1q/Catchem-PoGo#1239]
When i updated to the latest version i'm getting this message

[01:27:39] (ATTENTION) Character is too busy, proballby you are trying to do 2 or more actions at the same time! Please, try later! If you didn't do anything - ignore that message

**Comment by Cryptologism** [comment]
First of all... Dont overfload your char by many task cuz it was not inhuman example while catching pokemon you able to rename or eveolve pokemon... Well thats not normal... Why because to avoid triggered from niantic server...
Second.. Did you just notice on late version,sir Lunatic already put the sign like a RECYCLE sign in the tab of yours pokemon which located bottom right?..?
Why?? Because that button was use to reorder or refresh all task that you command you char to do it safely each task and more like human and logically...
Try to look into previous thread or  use search button before post thread..
Thx you.. Happy Botting...

**Comment by Lunat1q** [comment]
SRSLY?
I wrote: <b>"If you didn't do anything - ignore that message"</b>
.... wasn't that clear enough? should i write: <b>"Don't create issue on git"?</b>
