### ISSUE TITLE
[23:32:31] (ERROR) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by Sto7mz** [Lunat1q/Catchem-PoGo#1342]
Hi there i been getting this every 30mins to 1hour i get this over and over any idea why ?

Should i be worried about it? 

Or is it all okay just loose connections time to time ? 

I run 4 accounts but i run one at a time and wait 30mins before changing to another account.

Regards Matt

**Comment by Cryptologism** [comment]
Ermm still on the same ip... Better be cautious dude... You gonna be ip banned... It safe to use 1 ip 1 char

**Comment by Sto7mz** [comment]
Oh is that why it keeps coming up? Strange didnt know had to be different ips that why i wait 30mins before switching to another account so i need to download a poxy ip ?

**Comment by kingsley7601** [comment]
yes you do

**Comment by kingsley7601** [comment]
but you dont really need to have a proxy if your running one at a time but try to find or make one anyways

**Comment by Sto7mz** [comment]
What best proxy to use Kingsley ? and yeah i gonna use it now to be safe.

**Comment by Spk345** [comment]
If you are getting throttling calls every 30 mins to an hour, you need to Increase your bots delays. You are fine to use the same ip address as long as they are one at a time. I have run into no issues switching between accounts after a week. Some throttling calls will happen, usually whenever you are doing too many things at once, but sometimes just because their servers might hiccup. It's fine if it's here or there. 

I advise against free proxies because they are open to everyone and tend to be ip banned. "If you thought of it, who else has" mentality. 

For paid proxies I recommend:
https://www.sslprivateproxy.com/billing/aff.php?aff=684
Just click on Our Solutions And click on Pokemon Go Proxies.
POKE20 is the code for 20% off

**Comment by kingsley7601** [comment]
yea there arent many really many good free ones and as of right now there are no such things as perma ip bans so dont worry if you do get banned on ur normal cause they only last between 20mins - 3hours

**Comment by Sto7mz** [comment]
Okay no worries i havent had any other issues as in catching,running away etc or pokestops issues.

 I made all my pokestops,catching lower then most people may  set them at.

And i have made mine at 42 pokemon an hour and 62 Pokestops an hour but i normally stop the bot around 1hour max anyways before it normally reaches the stop limit and dont run that account till a day later only run them once a day only.

I have Smartdns not sure if that can be use as proxy https://www.smartdnsproxy.com/ is what i use for my netflix etc.

And thanks guys for fast replies.

And should i change all my 4 to proxy and should be fine ? or should i just be careful without it and just run them 1 hour apart instead of 30mins and it dosent always happen sometimes i can run for 1hour before it shows up sometimes it dosent show. 

I just want to be safe as a possible with 4 accounts 3 different teams and spare one if one get banned etc.

**Comment by Spk345** [comment]
Smartdnsproxy is indeed a proxy. VPN stands for virtual network proxy. As long as it supports SSL encryption it will work. Rule of thumb is one bot per ip address, it limits the chance of ip bans. 

IP Bans are temporary but can last from 2hrs -48hrs. By changing your ip address, you can circumvent it. You can usually request a new ip address from your proxy service or cycle your router to hopefully obtain a new ip address (if you ip banned you home wifi for example).
