### ISSUE TITLE
[Feature Request] Display if the pokemon got the best attacks

### ISSUE THREAD

**Issue by pedrogalv** [Lunat1q/Catchem-PoGo#1376]
Great fan of your work, and your bot is working really well.

I know that your bot can calculate IV's, but could be possible to check if the pokemon got the best moves?
Just for explanation purposes, check Blastoise attacks:

https://pokemon.gameinfo.io/pokemon/9-blastoise

his main attack is ramdomly selected between 3 moves, and would be nice to know if my pokemon got the best attack/dps.

If you want, I could check or create a JSON containing the best moves for each pokemon.

**Comment by Spk345** [comment]
The only downside to him making a static database for "best" moves is that if Niantic decides to Rebalance the game again, like they did a month ago, all that information would have to be updated. Not only that, but because they introduced and removed some fast and special moves, that would make it a large database that he'd have to code. Your best bet would be using:
https://thesilphroad.com/research

**Comment by pedrogalv** [comment]
Things change. And will always do. Our job is to keep up with niantic, they did the same with their API. Just because things change, there is no excuse for not implementing.

There's no need for a static database, just a simple JSON file, nothing fancy with data history or querys. And a single crawler can take the job of update the moves. And for the number of pokemons that they have yet.. it would be complete in a matter of seconds. As a developer i dont see any trouble implementing this, and I am willing to help, if you guys want!
