### ISSUE TITLE
Closed Source Code

### ISSUE THREAD

**Issue by MichaelHaushofer** [Lunat1q/Catchem-PoGo#1440]
Hi, 

i ve some thoughts about your closed source code.
I know that you want to protect your work, want to avoid that the bot is selled and i dont even have another solution for your problem. 

Edit: Why you dont try the idea from "Avoid code selling #1391" for two weeks or so before closing source ?

There will be no real way to identify (future) malicious code.
I see that the releases are clean and also virustotal.com says that.

But for example virustotal says "1 / 56", will you provide the full src so i can check that and compile by myself to doublecheck that ?

Thanks !

Edit:
duplicate of "How to ensure security of info now it's closed? #1408"
Sorry, haven't seen that before

**Comment by Lunat1q** [comment]
No i'll not provide anything. If you will see any problems with virustotal - you should PM me with check link, so i can determine, which module is getting false-detection.
I'm sure about the things i do, if you don't belive me - feel free to start APP on VM with wireshark or whatever you want.
There is 2 precompilled modules in that project for a month, and noone ever complained about that. Those moduler are hadly able to be reverse-engineered, but noone is saying they are bad.
While Catchem can be reversed in 1 click to see the codes, people start to whine about "omfg he closed the sources".
Letting you know:
I added lines with links, but in OpenSource project, the are too easy te be removed.

**Comment by michael-herwig** [comment]
I think you both have good points, but I don't think either closing the source code is the right way to go for several reasons.

1. As @MichaelHaushofer  mentioned it makes it harder to verify your source is harmless.
2. It is harder for people like me to get in touch with the code and add new features, bugfixes and so on, which (of course) would be committed back. As a result your program will evolve much slower than other open source projects and will be less reliable.
3. There are several other ways to secure your code. If you do not want your code to be sold pick the right license. Otherwise I do not know why you care about other selling this software. You said this shall be opensource and everyone should be able to do their own stuff even if this means selling the bot. If you do not want this you maybe want to sell the bot yourself?

Cheers

**Comment by Lunat1q** [comment]
Wanna know how many proper bugfixes via PR i received for a month of open source? 1.

**Comment by michael-herwig** [comment]
Hmmm this sux... anyhow the problem remains and i do not think you can keep up alone with features and bugfixes. If you need any help you can contact me. Anyhow good luck and thanks for your work.
