### ISSUE TITLE
No IP ban but no pokestop found in manhattan

### ISSUE THREAD

**Issue by gambleroflife** [Lunat1q/Catchem-PoGo#1454]
There is no IP ban for sure yet I still get this warning "[02:55:19] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?"

**Comment by johnpeterphoto** [comment]
it is a bug in 1.5.1:  use custom route and the pokestops will appear

**Comment by Spk345** [comment]
If you are using Release 1.5.1.0 and having issues with pokestops registering, downgrade to 1.5.0. I haven't been able to duplicate this issue, so any information you have would be useful.

**Comment by angelaayer** [comment]
have same error. No pokestop found

**Comment by Spk345** [comment]
GIVE ME SOME MORE DATA TO RECREATE GUYS.

**Comment by angelaayer** [comment]
As i said. I am not softbanned or ipban. I can use perfectly the old release. Just having problem with this update that is not showing pokemon and pokestops even when i use different custum routes

**Comment by dugarila** [comment]
I don't know if it has anything to do with the altitude value but I notice when that happens to me that the value of the altitude is either very high or very low, and probably because of that the bot doesn't recognize any pokestops. What I do to fix is stop and close the bot, then restart and input a decent value for the altitude and run it again.

**Comment by Spk345** [comment]
It appears to be an issue with transferring over your custom routes with your profiles. Turn off using custom routes before you switch over the profile. You can switch it back on afterwards, but transferring it, it refuses to load right away as it should.

**Comment by Spk345** [comment]
#1458
