### ISSUE TITLE
non pokestop found

### ISSUE THREAD

**Issue by angelaayer** [Lunat1q/Catchem-PoGo#1455]
there is no notification of non pokestop but it doesnt show any pokemon neither pokestops. Not working good this version. 
Anyway the features added are very good.

**Comment by Spk345** [comment]
Does it work in old release? If not, you have an IP ban. 

Otherwise, make sure custom route is set to off and try again.

**Comment by angelaayer** [comment]
old version works perfect including all the 4 routs i created before. Just this last one i have the problem of non pokestops and non pokemon.
Im not softbanned and no ipban its just a problem of new release

**Comment by kevindevm** [comment]
same here

**Comment by Spk345** [comment]
Okay, so when you transferred your old profile to the new, did you still have "Use custom route"? Because that is what is causing the issue. Turn it off when you switch profile over. It's having issues immediately loading it. Then turn it back on and select which route to use. Does that fix the issue?

**Comment by HernestoSanchez** [comment]
Sup guys. We already had another topic about this bug. Please keep all the questions there.

#1454 

Thanks!

**Comment by Spk345** [comment]
#1458
