### ISSUE TITLE
[Feature Request] More route creation features

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1612]
1. any way point can be setup as a starting point.
2. walking direction can be either way.
3. stop at end point

**Comment by petoe93** [comment]
walking direction is already possible both ways..i think the bot was running backwards for me sometimes after restarting the bot.
3. point actually makes sense for me, this would be really nice :)

another suggestion maybe: edit waypoints?
because now when you delete a waypoint from somewhere in the middle and put another one there instead the bot recognizes it as the latest waypoint and creates some really weird routes sometimes ^^

**Comment by jahknee** [comment]
Another suggestion is keyboard shortcuts for adding a way point. It's really tiresome to right click and then click on "add waypoint". This feature would save alot of time.

**Comment by TiksTriks** [comment]
Hi,

Another ideia is when creating the route (if logged in or not), show the pokestops on the map.

It would be far easier to determine our best waypoints.

Thank you!
keep you good work!
