### ISSUE TITLE
why after 20-30 min the bot dont do nothing just walk 

### ISSUE THREAD

**Issue by paparino** [Lunat1q/Catchem-PoGo#1673]
is the 3rd time today that i open the bot and after 20min  just walk ,pass in front a pokestop without do nothing,if i close it  when i open it i have just the route but nothing else ,nothing pokestop and pokemon just walk on the route

**Comment by paparino** [comment]
now i'm looking without the trace of pokemon i've got and it seems working much better

**Comment by Cryptologism** [comment]
`is the 3rd time today that i open the bot and after 20min just walk ,pass in front a pokestop without do nothing,if i close it when i open it i have just the route but nothing else ,nothing pokestop and pokemon just walk on the route`

I think it was because its been update dude... Check the latest news about pokemon go... Maybe u shoud stop botting for moment until it its safe again

**Comment by paparino** [comment]
1 hour without any error and still catch poke

**Comment by Cryptologism** [comment]
me too but seems like the pokemon was decrease minutes by minutes...  *use on test acc*

**Comment by paparino** [comment]
and with 2 bot working together ,is not the update because is like this in the last week ,i dowload the bot 1 week ago ,it was always like this after a while crash all ,the pokestops disapears ,i've tryed to restart the pc ,the internet modem ,but nothing ,after a while everything is normal ,looks like soft ban

**Comment by paparino** [comment]
but what the hell 6,7 soft ban every day hahaha

**Comment by alanearl** [comment]
Soft Ban
Use 1 public ip per bot
