### ISSUE TITLE
Question: is device come with the bot safe after new Update?

### ISSUE THREAD

**Issue by pokter75** [Lunat1q/Catchem-PoGo#1694]
Hi All,  with the new update from Nianticlab, is the device come with the bot in "device info" safe?  since they are testing and rooted devices?

" We continue to focus on eliminating bots and scrapers from Pokémon GO. Rooted or jailbroken devices are not supported by Pokémon GO. Remember to download Pokémon GO from the official Google Play Store or iTunes App Store only. "

http://pokemongo.nianticlabs.com/en/post/ver-update-091016/

**Comment by tyu366** [comment]
I think after that, there will be root bypass apk
Also there will be some tools to hide the root privilege.

My problem is I can only upgrade from 33 to 35 and cannot logout.  Otherwise I will not be able to login again.  It will hang infinitely after choosing google a/c.

I uninstall the official app and install the tutu version 0.33 app.  Its hangs in the the same way.  The tutu 0.35 version also have the same result.  If I login as PTC, any app either tutu version or official version, 0.33 or 0.35 are running smoothly.  

The cause and resolution remain unidentified.  It is however, it can play the original app by restore apk with data.

**Comment by pokter75** [comment]
Thank you for yr reply.
So it is better to wait until new release come out when api fixed.

**Comment by Spk345** [comment]
#1704
