### ISSUE TITLE
[Bug] xp / h calculator Problem

### ISSUE THREAD

**Issue by nataku-no-suna** [Lunat1q/Catchem-PoGo#1783]
Hello,

I have the impression that the xp / h calculator does not work properly, because I put the filter has: no more 5000xp / h and when I look in information I have at least 40 000XP / 3 hours.

Can you take a look?

Regards,

**Comment by nataku-no-suna** [comment]
start : 60 095 xp  filtre 4500 xp/h

![pogo2capture](https://cloud.githubusercontent.com/assets/4161827/18546406/1763de78-7b3e-11e6-8b27-739d3291eb2c.PNG)

10 minutes later :+1: 

![pogocapture](https://cloud.githubusercontent.com/assets/4161827/18546381/f3b48eaa-7b3d-11e6-96c6-69e147ecd99e.PNG)

5500 xp but the bot don't stop.

Regards,

**Comment by DGLVCY** [comment]
i'm catching few pokemons like 12 p hour... Can you help me????

**Comment by Spk345** [comment]
The question is do you have *evolve pokemon* or *use lucky egg when evolving *checked because that will skew your hourly xp gains massively, and it will also cause your bot to go to pause mode for max pokemon per hour, and max xp per hour. *This is intentional.*

All of the limits for settings are based on the max pokemon, etc. for a 23hr period of time.

**Comment by nataku-no-suna** [comment]
Thank you for your reply. Now I understood the principle.

ps: DGLVCY it depends on the area where you are, if there are not many pokemon that pop, goes to another area.

Regards,
