### ISSUE TITLE
Best info shown is wrong in 1.5.3.0 bld 54 when prioritize both IV and CP

### ISSUE THREAD

**Issue by tyu366** [Lunat1q/Catchem-PoGo#1904]
```
[23:29:48] (TRANSFERRED) Shellder     - CP:  435  IV:  64.44%  [Best CP:  567  IV:  57.78%] (Candies: 257)
CP  IV% 
567 57.8 (reported best)
454 31.1
471 84.4 (actual best) 
```

the problem persist in bld 54.  No improvement observed #1901

**Comment by Spk345** [comment]
What likely is happening if you are not using Poke List Transfer Filter (Right Column), is that because you prioritizing both CP AND IV, this Shellder is not meeting *both* of the transfer min criteria.
![TRANSFER CRITERIA](http://s9.postimg.org/rvxxr0o4v/screenshot_16.png)

For me, if a pokemon had less than 1250 CP *and* 95% IV, *and* wasn't on my Transfer Filter, it would transfer this when it starts its Transfer/Recycle routine, because it doesn't meet my criteria.

I will admit that "Duplicates" is misleading, due to the fact that if you choose 0. you would be left with an empty inventory (Unless you use Transfer filters, since that OVERRIDES every other transfer setting). 1 duplicate means only one Pokeman per type. and 2 means 2 pokemon, etc.


Now if you are meaning that the reported best is very different than what you have encountered, at least on this pre-release, that is most likely due to the fact that the data is most likely saved in your database from a prior run.

Does this help any?

**Comment by markfell** [comment]
I don't no u have sent me two much texes


Sent from my HTC

----- Reply message -----

**Comment by saldotman** [comment]
If I want to keep best CP rather than IV,
as well as keep IV higher than 98% (whatever their CP),

how I should pick the options?

**Comment by tyu366** [comment]
>What likely is happening if you are not using Poke List Transfer Filter (Right Column), is that because you prioritizing both CP AND IV, this Shellder is not meeting both of the transfer min criteria.
TRANSFER CRITERIA.

I imagine that the transfer filter is a setting for individual pokes while those not on the list takes the global setting.   Is it true?

**Comment by Spk345** [comment]
@tyu366 This is true, however you can add and delete pokemon from Transfer Filter List as much as you want.
