### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by icsusan** [Lunat1q/Catchem-PoGo#1906]
Hi guys.

Since yesterday I have been experimenting the following behavior:

![image](https://cloud.githubusercontent.com/assets/1584028/18640266/f3631404-7e5c-11e6-95cb-75899a963e1c.png)

The bot looks like "freezed" to login.

Yesterday was with an old account (level 20)...so I thought that I was banned. But today I tried with a new account (level 0), just created, and is the same behavior.

I tried with (first) and without proxy (then). And I waited 10 minutes approximately.

Thanks in advanced.

**Comment by Halitz** [comment]
Lo mismo con la ultima version V1.5.3.0?? Probar por favor.

**Comment by Halitz** [comment]
Same with the latest version V1.5.3.0 ?? Please try.

**Comment by Halitz** [comment]
With the new version the root phones are locked, you can change the device info? Could be?

**Comment by icsusan** [comment]
I am using 1.5.3 version

![image](https://cloud.githubusercontent.com/assets/1584028/18646021/4b873102-7e75-11e6-82db-4caab1e1e5ac.png)

I dont know why UPDATE info says 1.5.2.1 =(

**Comment by icsusan** [comment]
Uhmmm my phone is not rooted

**Comment by Spk345** [comment]
Logging in after updating to newer release versions can take a moment when Catchem has to sync up all data on bot profiles, connect to routing services, and there's also a 5 second delay so you can make sure your Coordinates are correct before it continues logging in. 

The newest pre-release does show as 1.5.2.1 for whatever reason, I have the newest release candidate and I notice this as well (I am a tester so I'm one RC newer).

I see you are using a proxy, using a proxy can make Catchem take a little longer, especially depending on your internet and the proxy you are going through. I haven't had any long waits using my proxy, so that seems rather odd that it's taking almost 10 minutes to get up and running. This might be due to unstable internet connection, since Catchem requires a very good connection to function properly and sync with POGO servers.

**Comment by Spk345** [comment]
Try switching your routing services, as that might be an issue causing for such a long hang-up. Mapzen tends to allow less API calls per day than Google, but both are free and easy to setup.

**Comment by icsusan** [comment]
Well...after some attemps I can log in...Ufff I thought that my account was banned. I dont know what happened. Maybe a soft ban? I dont know. Thanks you so much for your help and comments guys.
