### ISSUE TITLE
Altitude Issue (again u.u)

### ISSUE THREAD

**Issue by LeMoo07** [Lunat1q/Catchem-PoGo#1913]
I've been noticing a bad trend with the altitude.

The altitude goes to a fixed number set to 2243, but at this altitude the bot can't find any pokémon nor pokéstops.

When i force move the bot it resets the altitude to 10, at wich the bot actually recognizes pokémon and pokéstops.

**Comment by Bay101** [comment]
what routing service are you using? are you using mapzen elevation API?

**Comment by Spk345** [comment]
I'm just going to assume you are using Mapzen API key.

Your altitude data is generally saved to your local database, so if you've been to an area that has been called for before (because altitude rarely changes), it's pulling this information from your database. If you have used this area before and your database data is saved incorrectly, I would remove the database, after closing Catchem, and restart Catchem entirely, it will make a new .sdf database file and it will call to Mapzen for correct information, and save it correctly. Your database is called "CatchemDB.sdf" in your config folder. When you remove this database, all your collect info on pokemarkers/heatmaps/pokestops and altitude data will be removed. If you want to keep any of this data, I'd save it in another place for safe keeping.

If you haven't been to this area before, what likely happened is that you managed to hit your cap for calls to MAPZEN causing a ban on the API Key. This happens sometimes, and sends bad altitude data to Catchem when it's requested. I have never banned my keys before, but I know it is very possible to do. You can try regenerating a key on Mapzen, and see if that fixes your issue, or you can create a new developer account and generate a new key, that way.
