### ISSUE TITLE
NO usable Pokestops found in your area. Is your maximum distance too small? & Mapzen Valhalla API Key is Empty

### ISSUE THREAD

**Issue by MasterJared** [Lunat1q/Catchem-PoGo#1928]
Hi i would like to ask what should i do to fix this problem thanks

![image](https://cloud.githubusercontent.com/assets/22312176/18657580/2fb81c8e-7f2e-11e6-9499-d458c046062a.png)

**Comment by Spk345** [comment]
First of all... This is not a bug issue, or feature request, and there has been many closed issues about this.

Secondly, Mapzen how-to is on the Wiki, only difference now is that in the newest pre-release, we have simplified Mapzen routing service to one key box, since Mapzen unified their keys into one, IE you only need one key for elevation and Valhalla.

Thirdly, No usable pokestops is either due to too high, or low of altitude, or an IP ban. If it's reading as too high/low of altitude, then you need to check on your limit for Mapzen Elevation if you have one already. If that's not the case, then you have an IP ban, which is temporary and will lift in 12hrs max, and that is most likely due to too many bots on the same IP address or proxy at once. We recommend no more than one bot per ip address or proxy, and do not recommend using a free proxy or vpn service as it is usually always IP banned. Easy fix? Reset your router and pray you have dynamic IP assignment.

In the future, visit us on the discord channel for help, or look through past issues with the search box.

**Comment by MasterJared** [comment]
Im really sorry i didnt notice you emailed me and thank you for the
response.
