### ISSUE TITLE
Bug no Catchem

### ISSUE THREAD

**Issue by digimon2016cast** [Lunat1q/Catchem-PoGo#1980]
Boa tarde! 
        Gostaria de reportar um bug que aconteceu durante meu período de uso do Catchem; recentemente peguei um Vaporeon com 98% de IV e as 2 melhores habilidades para atacar ginásios, fiquei muito contente e fui renomear o mesmo, selecionei a opção (rename selected pokemon) abriu a aba de texto para eu renomeá-lo, no entanto quando botei o nome e dei ok, o Catchen transferiu meu Vaporeon, e fiquei no prejuízo e chateado.
         Admiro muito o trabalho de vocês com a programação desse Bot, e estou reportando o bug para que possam analisar e sanar, para que não aconteça com mais players utilitários do empenho da vossa equipe, muito obrigado. Parabéns.

**Comment by ArchangelBr** [comment]
Ele não vai nem analisar se tu não escrever em inglês pelo simples motivo de que ele não vai entender o que tu disse... sugiro que escreva em inglês, mesmo que seja do google tradutor.

**Comment by Taqzoito** [comment]
O mano ai ta certo, inglês cara.

**Comment by yut00** [comment]
tbm aconteceu comigo mais foi com um lapras mas nao e bug eu que vacilei e nao coloquei na aba de proibiçao de transferencias oq deve ter ocorrido com voçe tambem.

**Comment by pedrodobal** [comment]
(Translated)

Good afternoon!
I would like to report a bug that happened during my Catchem usage period; recently caught a Vaporeon with 98% IV and the 2 best skills to attack gyms , I was very happy and was renaming it , I selected the option ( rename selected pokemon ) opened the Text tab for me to rename it , but when I put the name and gave ok , the catchen transferred my Vaporeon , and I was at a loss and upset .
I admire your work with programming that Bot, and I'm reporting the bug so that they can analyze and remedy , lest more utility players the commitment of your team , thank you. Congratulations.

**Comment by Lunat1q** [comment]
That can't happen since Action Queue is implemented.
