### ISSUE TITLE
[Bug] [Catchem 1.5.3.0 build62] Egg list and Pokedex disappear

### ISSUE THREAD

**Issue by kirimkefadil** [Lunat1q/Catchem-PoGo#1992]
Egg list and Pokedex display disappear after stop and start. sometimes in long time use, it wil disappear. for egg can be show after click refresh button, but not pokedex
![2](https://cloud.githubusercontent.com/assets/21058672/18738622/908ef7c2-80c7-11e6-88be-9bac096b514a.jpg)

**Comment by Spk345** [comment]
This is solved by restarting catchem.  Was this your first time running newest version catchem?

**Comment by medoamanquer** [comment]
same here
it needs to be fixed

**Comment by Spk345** [comment]
Okay, straight from lunatiq:  pokedex takes a moment to cache all pokemon caught and add to pokedex tab, it will take a moment because upon startup it's running ton same of other routines. This is normal! Good news is, you can still view your pokedex once cached after you full-stop your bot. Hooray! Just be patient.

**Comment by hotmetal007** [comment]
i dont have the pokedex tab T.T 1.5.3.0 :(
