### ISSUE TITLE
Servers unstable

### ISSUE THREAD

**Issue by LalalaMan** [Lunat1q/Catchem-PoGo#2014]
I faced the problem shown as below

[15:04:10] Niantic Servers unstable, throttling API Calls.
[15:04:10] [NIANTIC] Expected 5 responses, but got 0 responses

sometimes 

[20:24:49] Niantic Servers unstable, throttling API Calls.
[20:24:49] [NIANTIC] Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.

This message appears every 30mins. I can catching and looting pokestop normally.
As I know, if the account got banned, it will shows Expected 5 responses, but got "1" responses. Now, mine is got 0 responses, what does it mean?
Should I stop botting now? Is it a signal about account ban nearly?

**Comment by Spk345** [comment]
I had that a couple days ago. Just pause your bot for a while and see if it fixes itself.

**Comment by LalalaMan** [comment]
How to fix? 
Any reasons cause it appears? Moving too fast or something wrong with my routes?

**Comment by Spk345** [comment]
It's most likely caused by unstable internet connection, and issues with POGO servers. Generally when you get throttled is because your bot lags and then does a bunch of calls to the servers, which then leads to bot being throttled. Pogo Servers have had a lot of "bad" requests sent recently, we are not sure why. 

My bot was fine when I logged in on a mobile device, so it's not a ban.
Just pause you bot for a little while and try again.

**Comment by LalalaMan** [comment]
I see. Thank you very much Spk345!!
