### ISSUE TITLE
pre release

### ISSUE THREAD

**Issue by kobbey21** [Lunat1q/Catchem-PoGo#2047]
I tried this new release, at first, it seemed alright but now I get soft banned after a few minutes of botting.
Probably has something to do with the new game update. Back to using 1.5.2.1.

**Comment by Spk345** [comment]
You shouldn't have been soft banned because of upgrading to 1.5.3.0. The only how softbans happen is that 1.) using too many bots on same IP, 2.) Your altitude info is incorrect and you are too high or too low below altitude and therefore cannot *see* pokestops, or 3.) You teleported (moved to quickly from place to place) or were moving too fast. There's also a possibility you screwed up your delay settings.

What I am saying, **is that this is out-right impossible.**

And even more so, because you dropped back to 1.5.2.1. which runs the same API as 1.5.3.0, and it *now works*.
