### ISSUE TITLE
[Possible bug] MobBotRouting API Key is Empty!

### ISSUE THREAD

**Issue by isPhelipe** [Lunat1q/Catchem-PoGo#2052]
![sem titulo](https://cloud.githubusercontent.com/assets/22429439/18815798/8fa4e2e0-8310-11e6-84f9-2b1f961c017e.png)

My bot is always so, why?

**Comment by Spk345** [comment]
## First of all, README #1960 .

Second: Upgrade to the latest Pre-Release available [**here**](https://github.com/Lunat1q/Catchem-PoGo/releases), since you are using a far out-dated release.

Third: There's even a wiki about how to get one of the two free routing services, I suggest Mapzen because it's the easiest. Read that [**Here**](https://github.com/Lunat1q/Catchem-PoGo/wiki/Mapzen-Unified-API-Key).

**Comment by isPhelipe** [comment]
I have been using the latest version, now I used the mapzen and after a while it just gets so
![sem titulo2](https://cloud.githubusercontent.com/assets/22429439/18833344/8eef4456-83c6-11e6-9bc3-4db5036a9035.png)
