### ISSUE TITLE
No pokestop fou

### ISSUE THREAD

**Issue by Harflute** [Lunat1q/Catchem-PoGo#2108]
Hello, I have worries I have they are two messages: [14:40:38](ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?     But i'm in a big city with a lot of pokestops
[14:41:38](ATTENTION) MobBotRouting API Key is Empty!
 who appears as soon as I launch the game the message "14:41:38] (ATTENTION) MobBotRouting API Key is Empty!" returns to him several times somebody can helped me? 
Sorry for my approximate English

**Comment by mrbigshot29** [comment]
the apikey is because there is a missing api key entered in the settings screen, however thats the least of the problems. the no pokestops is a temporary ban (used to be from to many separate requests from a ip address (using more than one bot in catchem). the temp ban was usually one hour but could be longer depending. the new update has a captcha that the bot cannot enter yet so you play for a while and the bot no longer can find poke stops, if you restart the bot you find the missing poke stop warning.

if you log into your account from your phone (3.5 hours after a previous location if far away or else you get banned) you will have a warning screen on your account show up.

**Comment by Harflute** [comment]
Ah of agreement thank you, I use only two bot one in my country and another which goes to America (that I I use very little)
 Time that I would put in the car to return to me has the place of bot and time that I put before me reconnected on my phone
Concerning api key how regulated this concern?
 thank you 
and sorry for my english again

**Comment by cajardim** [comment]
I have a some problem, but in my phone is work fine, the message: No usable PokeStops found in your area. Is your maximum distance too small is soft ban?

**Comment by rafaelsccp** [comment]
I can't use either. Same problem.
