### ISSUE TITLE
[Feature Request] UI: display eggs color/poke list/poke xfer

### ISSUE THREAD

**Issue by devgraal** [Lunat1q/Catchem-PoGo#2171]
Hello !
HEre are some really minor requests ;)

- Could it be possible to display differents kind of eggs in the UI based on their distances ? (as it is in the game)
- Is there a way to block transfering favourites poke in the UI (also like it is in the game) ?
- Is there a way to use rariety of pokemons instead of their names in the list ? ie: common/rare/very rare/legendary

thx all dev to your great work !

**Comment by Spk345** [comment]
1.) There's currently no assets available for newest POGO. Due to this, we do not have the newest Eggs. Once they are available we will update them in Catchem.
2.) If a pokemon is favorited, you are unable to transfer it. If it does transfer a favorited pokemon that would be a bug, and not intended.
3.) Rarity is subjective and is unofficial. Niantic has not released anything about the actual rarity of certain pokemon. We also have a Pokedex tab that already lists this information anyways.
