### ISSUE TITLE
lured pokestops

### ISSUE THREAD

**Issue by gambleroflife** [Lunat1q/Catchem-PoGo#289]
it would be great if the lured pokestops are recognized. I mean it recognize the lured ones in a close area but after that none. So lured pokemons cannot be catched. It makes huge diffrence on XP/HR.

I think the main problem here is the refreshing map is not take lured ones into account.

Update: There is lure or normal type when you see a pokemon. I think this solves the issue.

**Comment by Lunat1q** [comment]
it have Lured info while running, that info just doesn't update on the map, not sure i'll create update pokestop feature, but... ok let's plan it

**Comment by madgar29** [comment]
I think camping lured pokemon stops for pokemon is not only a great feature to have but a safe one. let's just call it very human like because that's what most players do they lure pokemon stops and they sit in groups and catch em, I am sure I am not the only one that has actually gone outside and done it. But maybe make a slow small walking around the pokestop for maximum effectiveness?

**Comment by gambleroflife** [comment]
But I don't think lured pokemons is shown. Right?

**Comment by DanyBoyGH** [comment]
Farm walking around on lure spots are the more human like behave we could have. But, looks like the bot cant see lured pokemons at all. That need a fix and we should be able to set a Farm Area or Max Distance From Start Point. Set move speed to 0.001 works to be freezed in same spot, but that isnt a human behave and dont help with eggs. Program to eventualy whalks around will be more humam like and will works fine with the eggs.
btw, Tanks for the efort!!

**Comment by madgar29** [comment]
you say the bot doesnt pick up lured pokemon stops but i see the icon or the pokemonstop lured in the bot so its obviously visual to the human watching the bot how is would it be hard for the programmer to notice these on the map? im not a programmer i wish i was i know its work im just asking why is this hard or not possible when the map even shows lured pokemon stops.

**Comment by DanyBoyGH** [comment]
madgar, what you see on the map are the Lured Pokestops, but the pokemons that respaws because the lure dont apears. I made a test, botting in same place I was fisicaly with my phone on another account, on the phone, a lot of pokemons respaws and the bot just dont notice them.
Prob, are 2 diferents kinds of respaws, the regular respaw and a special respaw for lures, and prob the bot dont identify this last one.

**Comment by madgar29** [comment]
oh its the spawning itself thats strange

**Comment by medoamanquer** [comment]
If the bot could  spot  lured pokemons  it would be great

**Comment by JinxGenius** [comment]
I saw there're lured pokemons in the log, just need to think a better movement sets to keep rolling around those pokestop

**Comment by poke5544** [comment]
I would also like to see Lured Pokestops recognized in the bot. The bot doesn't recognize all of the pokemon from the lure only pokemon outisde the range of the lure. I really hope this feature gets included in a future update. I am not good at coding but I do have good GPS coodinates for a test site if you would like them.
https://github.com/Lunat1q/Catchem-PoGo/labels/enhancemen
https://github.com/Lunat1q/Catchem-PoGo/labels/feature%20requestt

**Comment by DanyBoyGH** [comment]
JinxGenius, there is lured pokemons on the log, but I saw in real (augmented) life some pokemons the bot just dont saw. Try to put the bot and a phone with fake GPS on some massive lured place, like Central Park (NY). On the game with fake GPS will apears some pokemons that bot cant see.
