### ISSUE TITLE
Bot does not reach the end of track

### ISSUE THREAD

**Issue by 4vizz** [Lunat1q/Catchem-PoGo#327]
Bot does not reach the end of track which cause option "snipe at pokestops" doesn't work because it collect pokestops before it arrives to them
http://imgur.com/U6lTTUs

**Comment by pikopike** [comment]
btw. you dont want to snipe XD

**Comment by 4vizz** [comment]
all my mains acc that i cared about are banned so xD

**Comment by standujar** [comment]
ahahahah, dont swipe, I'm using Catchem since level 1, i'm level 26 atm, using 4-5h a days, with log on/off every 25/30 min, with 40 pkm, 60 pkstop every hours, minspeed : 4km/h, maxspeed : 10km/h, in central park and mannathan port. I'm using the bot only when I'm in front of my computer. 

Atm : 0 softban, 0 ban, 0 unknown error but Niantic one.. (logic error)

Take care when you're using bot, and check your screen every 30 min :)

**Comment by 4vizz** [comment]
Ye, I know that sniping is very risky but I just want to know how to fix it :P I won't snipe like crazy but it's annoying a bit when (i don't know) map isn't accurate
