### ISSUE TITLE
Niantic Servers unstable, throttling API Calls

### ISSUE THREAD

**Issue by GiulioKS10** [Lunat1q/Catchem-PoGo#428]
Hello Guys,

Someone knows what means the message bellow?

[17:43:25] (INFO) ====== DisplayHighestsPerfect ======
[17:43:25] (INFO) >   CP/BEST/POWERED |	perfect	| LVL | NAME       | MOVE1              | MOVE2  | MoveRankVsAveType |
[17:43:25] (INFO) Highests Pokemon List is empty
[17:43:40] (ERROR) Niantic Servers unstable, throttling API Calls.

So, the bot is just looping on this, any solution?

**Comment by madgar29** [comment]
I believe its the niantic servers acting up or getting DDOSed again, I do not believe its the bot at all. Give it an hour.

**Comment by TomWolker** [comment]
If the message appears at the beginning and  not continue progressing indicates that you have been banned . If appear during normal operation of the bot does not need to be afraid ... must be some miscommunication between you and the server ...

**Comment by lanrulezall** [comment]
I got the same errors.  I waited 2 hrs and still got the same errors.  I think it might be a ban.  I read on a discord channel that all bot up to now will get ban because the data from the bot api call is different from the official api.  So I guess, they can see the different between a bot and an official client.  I don't think if is safe to bot now, not until the bot dev fix the api to match the official client.  Can anyone confirm this?
