### ISSUE TITLE
Feature Request: Ignore Pokestop, Force Move Route, Wait

### ISSUE THREAD

**Issue by Akyoto16** [Lunat1q/Catchem-PoGo#599]
Hello thanks for reading this :)

First thing I request is the funktion to ignore pokestop (only catching) i think its a good funktion maybe.

Second is that you can create a route with force move on the Map (Maybe with Numpad Numbers 1-9) and the bot go to first,second and and and. (maybe a loop?)

Third is the funktion to Simple Wait (dont move) good to catch on Lured Pokestops :)

Have a nice day :)

**Comment by rcarrillom1410** [comment]
I think that the first feature you mention, was the way it worked on previous releases.

Concerning your second point, what you want is to use Google Directions, you can do exactly what you are saying.

If you want to stop on a PokéStop since it has a Lure you can always change the MaxTravelDistance to 0 km, I know is not really a solution but the thing is there is not that feature on the bot yet.

Greetings 

:)

**Comment by vanx254** [comment]
rcarrillom1410 :+1:

How do you create your own perzonalized route? I already use a Google Directions Api, but in my case is just used to auto create a route with 20 pokestops.  

Thank you

**Comment by rcarrillom1410** [comment]
Thats the only way, but I think that up to now it is good enough
