### ISSUE TITLE
Question about autoevolution.

### ISSUE THREAD

**Issue by vanx254** [Lunat1q/Catchem-PoGo#613]
Dev you are doing a great bot. Thank you.

I have a question. How it works evolution list? What is the right configuration if i want to auto evolve only pokemons in evolution list? 

**Evolve all Poke above IV**: When checked, this will evolve all Poke if the other settings conditions are met.
**Evolve IV value**: This is the Minimum IV value that the bot will evolve all Poke above this IV, if you have sufficient candies.
**Evolve all Poke with enough Candy**: When checked the bot will evolve all Poke if there is sufficient candy.

**Comment by renatodolce** [comment]
Good question, I also have this doubt.

**Comment by blackbakers** [comment]
Firstable i want to say a big thanks for the devs , your bot is awsome ! :)

My little issue is with the auto evolution , maybe there is no bug and i don't use it like it should be.
I want to evolved only the pokemon that i choose to in the tab "pokemon list setting" and "to evolve" and i checked the box "evolve all pokemon above iv" in the tab "settings" but the problem is in this configuration , all the pokemons above the iv that i fixed evolve regardless of my list "pokemon to evolve" but if  i don't check the box "evolve all pokemon above iv" the bot does not evolve the pokemons...

So my question is this, what can i do to make the bot evolve ONLY the pokemons that i choose to in the  "pokemon list setting" ?

Thanks in advance for your response
