### ISSUE TITLE
Trying to run the application on Linux

### ISSUE THREAD

**Issue by renatodolce** [Lunat1q/Catchem-PoGo#632]
I wonder what DLLs are necessary to run the application?? I will use PlayOnLinux, however it is necessary some dll to run it properly, so I would know.

**Comment by Lunat1q** [comment]
That app isn't developed for Linux. And will not be, if u wanna try it - do, if u will handle it, feel free to describe the way.

**Comment by renatodolce** [comment]
Okay that will not be developed for linux, so I'm turning to run, but I wonder what dependencies.

**Comment by ricardofago** [comment]
Most likely the same as others bots (Visual C++ Redistributables for Visual Studio 2015 and .NET Framework 4.6.2). Try it out and let us know.

**Comment by alanearl** [comment]
Try WineHQ :)

**Comment by eSPiYa** [comment]
The problem is this application is using WPF/UWP which is only present on MS Windows. Also the library for the map can only work on WPF and Windows Forms(deprecated already), I think.

I'm not sure if the author used .NET 4.x or the fully-opensourced .NET Core.

If it is .NET 4.x, you have to replace the GUI with other cross-platform library like GTK#. GMap.NET for sure won't work here.

If it is .NET Core, there is still no cross-platform GUI library for this. You may create one using OpenGL(through OpenTK) or make it fully web-based(ASP.NET 5, access it through your web-browser).
