### ISSUE TITLE
Character too busy

### ISSUE THREAD

**Issue by untesty** [Lunat1q/Catchem-PoGo#645]
[19:08:23] (ATTENTION) Character is too busy, please, try later!
[19:09:04] (ATTENTION) Character is too busy, please, try later!

Anyone who knows what this means? I get it sometimes and then the bot won't transfer pokemon, recycle items, catch pokemon and spin pokestops.

 It's like the bot is freezing or something like that.

**Comment by Lukaum** [comment]
I noticed recently that when you transfer more than one Pokemon , evolves more than 1 pokemon or does recycles the items , the character gets busy status. I do not know if it's because the game animation (if the pokemon ) , or the delay of Catchem , you can go to the settings to improve the experience delay - Delay With Evolve , Delay Transfer Pokemon , Delay Recycle Item, etc .. .

**Comment by hazmad** [comment]
did you set limits on how many pokemon and stops per hour in the settings?

**Comment by Bay101** [comment]
It is a new feature that is being implemented which stops multiple tasks being done at once :smiley:
