### ISSUE TITLE
Bot paused due to max xp per hour

### ISSUE THREAD

**Issue by Vaye1986** [Lunat1q/Catchem-PoGo#659]
Hi, when I pause the bot manually to start another bot and then i start it again some hours later, it will suddenly tell me that it got 90k xp/h and then pause itself again because it reached the max xp per hour and will go to sleep for 600 minutes. How do I fix this? Thanks!

**Comment by Lunat1q** [comment]
Should check that

**Comment by kamingsuun** [comment]
Hi my friends
This is my forth account, first three of them banned because of bots.. 
I don't want to loose this account again.. 
I would like to learn, "What must be max and min walking speeds not to be banned?"
Now I'm using "Min: 4 ; Max: 6" It's very slow.. After Level 21, It takes 20 hours to next level..
Can you share which speeds are u using? What are the safest speeds?

**Comment by impossibrubear** [comment]
@Vaye1986 i don't use the max xp/h, are you trying to use your "main" account to play? All i do is spoof accounts and let them catch whatever appears and then, if it's better then my actual main, i trade and put my former main as bot. I find that useless since bots can be detected easily (a friend of mine told me, but didn't explained, so....). Knowing that, i let them be bots and if they survive they come to the main area. But there's one bot i try this feature and it works nicely, yesterday it ran all day long and it keeps running now, without problems or whatsoever.

@kamingsuun the max speed, i've read it somewhere and saw many yt videos about other bots apps, is 35km/h, but since i drive a lot and pokemon stays on because there's a LOT of traffic here, i don't think you get banned for being "speeding". You must check other settings like the delays for actions, humanize throws' %, keep the bot following human paths and not flying, altitude and so on. Maybe, and this is a guess, it's not a problem of speed, since i let mine 15 to 30 in most bots (look at the answer i gave to OP) and my speed factor is always maxxed out.

Cheers!

**Comment by gamelordhacker** [comment]
im using to be safe @ min 5 - max 7  and change the Max xp per hour (from 10000) to (50000)

**Comment by Lunat1q** [comment]
fixed.
