### ISSUE TITLE
How to set grinding area range..

### ISSUE THREAD

**Issue by izon13** [Lunat1q/Catchem-PoGo#724]
I want to farm Magikarp but the bot keeps going away from the location i set...

**Comment by Rozjil** [comment]
i think you just need to set your max distance too maybe 5000m maybe

**Comment by talktonetto** [comment]
i'm with the same problem, dont matter the max range i set, he still walking to so far away of the world running to roll pokestops

**Comment by izon13** [comment]
I think that setting "Max Travel Distance In Meters" is for Teleportation.. I don't use that.. And i already set it to 400 just in case it affects the range of my farming area..

**Comment by hohooh0320** [comment]
hey,,Max Distance is work, noice if Discovery pathing is clicked.
Discovery pathing: Starts to discover location around, most optimized pathing at the momment, WILL IGNORE MAX DISTANCE

**Comment by Snurbsy** [comment]
Since releases 1.4.6.1 the nianitc serverrequests by the API are much more stable (much less "throttling API-calls"). In fact of that, it is possible to setup your framing/grinding area by using gpx-pathing.
Lunat1q wrote, that gpx is outdated and will be obsolete in next versions, but at this time its a nice feature to use in combination with mapzen elevation. No routing by google is needed.
