### ISSUE TITLE
Possibility of Hard Ban With IP ?

### ISSUE THREAD

**Issue by eloxxx** [Lunat1q/Catchem-PoGo#775]
Heloo guys, Firt of all thanks a lot for this amazing bot, I got level 22 without any problem.

I wanted to know something guys, 
As you may notice, when you start the bot, there is your IP which is written, so from level 1 to 22 I only botted near my house.
But I want to set other coordinates like central park, los angeles but is it risky to do that as our IP is written ?

So If I am living in Wales and put the bot coordinates at Central Park, is there any chance that Niantic catch me beacause of my IP that I am cheating ? Do they have acces to our IP adress ? 

Thanks a lot guys !!

**Comment by maxsofar** [comment]
I'm currently lvl 25, I've been to central park, santa monica and London - no ban.
You know, you can use proxy if you want to get local ip

**Comment by Cryptologism** [comment]
Its better to use same IP form low level until high level... that if use router unless you use data phone mobile... Dont look too obvious by jumping there or here.. mybe this can make you safe.. and yes niantic save our ip everytime we connect to their server..

**Comment by eloxxx** [comment]
Thank Guys, Maxsofar, I think you have been lucky so far be careful, as you said, its better to use a Proxy.

And yes, Cryptologism, if Niantic save our IP, we have to be careful about that, its a small detail but could turn into a big issue.

I will just try london, but i will use a proxy service for that, don't want to take any risk x).

**Comment by rudahml** [comment]
So, if I only use the bot in my city, but with a 10km of distance, from my house to the pokestops concentration. Can I get a Hard Ban?

**Comment by eloxxx** [comment]
Rudahml, definately no, don't worry about that, 
For now I use up to 30km and nothing happened

**Comment by sygul** [comment]
In my experience (limited) I can tell you I ran 4 accounts in parallel 3 in Aus and one in the US without using a proxy.  First day was fine. 2nd day received an ip soft ban, didn't realise at the time, as I was able to login and move around however no stops or pokemons appeared (bot actually complained no stops in range). Thought it may be a issue with a server than manages the stops. Cleared in a few hours. Then it happened again the next day. However tried using my phone (with WiFi off) and all was fine (same account), so knew it was a IP ban of some sort, anyhow a quick modem re-boot (so I get allocated new IP fixed the problem again).  So I now limit session to 2 hours.  Few things I don't understand what triggered the ban, was it multiple users on the same IP ? if so they could just as easily blocked the accounts rather than the IP, If they suspected a bot I guess they may have killed the accounts.  Given this senario even if you ran via a proxy in theory the proxy's ip would get banned so I don't think you really gain anything using a proxy.  It may stop Niantic from tracing you, though why would they ?. Storing you IP gains them nothing (other than detecting multiple users on same IP)  It's not as if your illegally downloading files or similar. Your just breaching their terms.  So personally I think using a proxy is an unnecessary overhead, if it makes you feel safer then no harm done.

Also have to agree great program, considering it does virtually everything the actual app can do with a "virtual human running the commands".  and developed I guess since the app was released just over a month ago.

**Comment by eloxxx** [comment]
Sugul, I think the cause of you ban is the multiple users on the same ip, but with different location I reckon.

I got also an IP ban when my bro set his Bot in the US and mine was in Wales.

I think it safe to use a proxy if you wanna farm far away from your home.

**Comment by RevGDFreeze** [comment]
Yep same here, keep them within the same country, even better run a VPN from that particular country to be more legit!
