### ISSUE TITLE
v1.4.8 Custom Routing Off Road.

### ISSUE THREAD

**Issue by alanearl** [Lunat1q/Catchem-PoGo#786]
Dear Support,

Please support off road routing on routing builder.
The idea is really nice to have a routing builder instead of using gpx file.
But off road routing is not yet implemented.
I just want to stay inside a mall.

Keep up the good work.

**Comment by hugoleosp** [comment]
It would be nice if we decide the route, like click and pinpoint some directions instead let the navigation system decide... sometimes we just want to be inside a park because people are using Lures.

And also a way to pause the player, so, if I find a lure active, I could just hit the pause button and stay there for a while just like we used to do when we we're out there playing pokemon go. =D

Thank you for your good work.

**Comment by alanearl** [comment]
Yeah agree the bot will stay at the lure pokestop like lazy humans do lols...

**Comment by hugoleosp** [comment]
not lazy .. it's expected people stop a while at Pokestops with lure, and it's ideal to stop to make some transfers, evolves, recycling... it's weird to do those things walking and catching pokémons at the same time, like, you throw a ball and transfer a pokemon, that's weird and Niantic will soon use this to check bots, how can someone change screens so fast between cathing attempts?

**Comment by Lunat1q** [comment]
Provide me Routing API which can do it, and i'll impement it.
