### ISSUE TITLE
Recycling items

### ISSUE THREAD

**Issue by ommeirelles** [Lunat1q/Catchem-PoGo#787]
My bot just stopped from Recycling items and i dont know why...

This happened after i replaced the 1.4.7 version with 1.4.8 version and rolled back to 1.4.7 after getting an issue on the latest version(the windows crash every time i  change any config).
Now i deleted the files and started again with the 1.4.7 version and the boot steel not recycle the items.

**Comment by ommeirelles** [comment]
i think that maybe the problem is in RouteService , i was using GoogleDirections and when i changed to MobBot  the recycling started to work again.

**Comment by vandroiy8** [comment]
It is only recycling at the end of the route it seems, with mobbot it is/was working, because the routing with mobbot had some error according to the logfiles (Routing error: The operation has timed out OR Routing error: Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.), which I think was fixed but now also requires an API key, so i haven't tried that yet.

**Comment by Lunat1q** [comment]
fixed
