### ISSUE TITLE
Is it safe to bot multiple accounts at the same time?..

### ISSUE THREAD

**Issue by izon13** [Lunat1q/Catchem-PoGo#802]
Is it safe to bot multiple accounts at the same time?.. I''m afraid my legit account will also get ban when they caught my bots,  because i don't use proxy.. I have tried all free proxy and all their ip is banned..

**Comment by chrislim80** [comment]
Please refer to discord channel

**Comment by alanearl** [comment]
Better not to bot in multiple accounts at the same time.

**Comment by impossibrubear** [comment]
perfectly safe, if you don't fear someone getting banned randomly. I lost 4 accounts but i think it was because i was trying tutuapp + hacked pokego (with joystick). Now i've been using many bots without a single ban. It's been 3 days now. All of them using humanize throws and stuff and 2 acc i try without these humanize stuff, just to try it out how fast they can grow.

**Comment by kingjman1994** [comment]
Not unless you're using a (different) proxy for each individual bot. You'll either get IP banned or the accounts will banned, but probably both.
