### ISSUE TITLE
Teleport = flee

### ISSUE THREAD

**Issue by strecdsw** [Lunat1q/Catchem-PoGo#895]
Whenever I teleport (pause bot + click where you want to go), gives "Flee" in Pokemon. What can it be? If I let the character walking, does not happen ...

**Comment by SoniMail** [comment]
It's a soft ban. Whenever you teleport Niantic can see that you walked a long distance in a impossible time, so it gives you a soft ban, which mean that you can not get items from pokestops and you can not catch pokemons, cuz' they will ALWAYS flee way.

You should stop using the teleport, in order to avoid soft ban and, in a near future, hard/perma ban.
