### ISSUE TITLE
Bot stops every minute

### ISSUE THREAD

**Issue by xelphy** [Lunat1q/Catchem-PoGo#992]
Hey folks,

I am using the newest version of Catchem PoGo Bot (v1.4.9.1). My Character stops every minute, often less, to check / update the inventory. On another board someone suggested to check if ""BeLikeRobot" is turned on true, but it isnt.

Does anybody has an idea how to fix this? The main problem is that my XP/H drops to 1-2k since of this pauses.

Best regards

**Comment by Eichhoernchen123** [comment]
Hi! I had the same problem. You just have to go to Settings, then go to "Items" and there is a box for "Recycle At Usage Percentage". It must be 0.85 for you. It means that when there's 85% of your storage filled with items, the bot is gonna check and delete what he should. And he will do it everytime your items reach 85% of your storage. So I wrote like 1000 instead of 0,85 because it will never reach 100000% lol. And he will never going to stop everytime the storage reach its limit.
Hope it can fix this :)

**Comment by fabntic** [comment]
Yes setting...
Some explanation...
A=amount of pokeball + potions + revives +berries 
B=recycle at usage percentage X 350 items in bag. 
A should be << than B
Example 
100+40+20+50=210 A
0,85x350=297 B
The difference is enough B-A= 87 item before next recycling.
Refer to #812 solution...
Maybe you make a changes in delay in checking the inventory
